#!/usr/bin/env bash
# Usage: git-mr: git merge(if ff possible) or rebase a remote branch with current branch.
# Example: git-mr [[$remote] $remote-branch-name]

cur_branch="$(git rev-parse --abbrev-ref HEAD)"
if [ $# -gt 1 ]; then
    remote="$1/$2"
else
    remote="$(git rev-parse --abbrev-ref --symbolic-full-name @{u})"
    test -z "$remote" && echo "Upstream no found. Maybe you need to specify remote name?" && exit 1
    test $# -eq 1 && remote="${remote%%/*}/$1"
fi

git fetch ${remote/\// }
base=$(git merge-base $cur_branch $remote)
if [ "$base" == "$(git rev-parse HEAD)" ]; then
    git merge $remote
else
    git rebase -i $remote
fi
